/** Slugs rendered via CustomToolOutlet (not the generic engine runner). */

export const FINANCE_TOOL_SLUGS = new Set([
  "simple-interest",
  "gst-calculator",
  "discount-calculator",
  "tip-calculator",
  "roi-calculator",
  "profit-loss-calculator",
  "salary-hike-calculator",
]);

export const HEALTH_TOOL_SLUGS = new Set([
  "bmr-calculator",
  "calorie-calculator",
  "water-intake-calculator",
  "body-fat-calculator",
]);

export const MATH_TOOL_SLUGS = new Set([
  "quadratic-solver",
  "pythagorean-theorem",
  "gcd-lcm-calculator",
]);

export const DATETIME_TOOL_SLUGS = new Set([
  "days-between-dates",
  "countdown-calculator",
  "week-number-calculator",
  "due-date-calculator",
]);

export const CUSTOM_TOOL_SLUGS: ReadonlySet<string> = new Set([
  ...FINANCE_TOOL_SLUGS,
  ...HEALTH_TOOL_SLUGS,
  ...MATH_TOOL_SLUGS,
  ...DATETIME_TOOL_SLUGS,
  "background-remover",
  "image-resizer",
  "image-compressor",
  "image-merger",
  "pdf-page-editor",
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "pdf-to-jpg",
  "rotate-pdf",
  "watermark-pdf",
  "organize-pdf",
  "pdf-page-numbers",
  "pdf-compare",
  "image-to-pdf",
  "text-to-pdf",
  "html-to-pdf",
  "xml-suite",
  "qr-code",
  "age-calculator",
  "bmi-calculator",
  "compound-interest",
  "loan-emi-calculator",
  "contrast-checker",
  "gradient-generator",
  "currency-converter",
  "html-preview",
  "base64-image",
  "string-inspector",
  "markdown-preview",
  "regex-tester",
  "uuid-generator",
  "http-status-reference",
  "css-box-shadow",
  "image-format-converter",
  "svg-optimizer",
  "exif-viewer",
  "unicode-checker",
  "mermaid-editor",
  "timezone-converter",
  "websocket-tester",
  "ipynb-to-pdf",
  "gitignore-generator",
  "license-generator",
  "env-validator",
  "dns-lookup",
  "ip-info",
  "npm-compare",
  "color-converter",
  "color-palette",
  "notepad-plus-plus",
  "expense-splitter",
  "video-converter",
  "gif-maker",
]);
